-- =========================================================
-- Corporate Client Gap Agent - PostgreSQL schema v1.0
-- 기준: DB 설계서 v1.0, PRD v2 (2026-10-08)
--
-- 설계서 대비 변경점
--   company.last_consulted_at        : PRD 4장 조회 기준 보조값(최근 상담일)
--   rm_plan.expected_precision       : 설계서의 precision (SQL 키워드 충돌 회피)
--   gap_analysis.query_ranges        : 계획별 실제 조회 범위 (설계서 4.3 주의사항)
--   gap_analysis.model_version       : LLM 추출 재현용 (설계서 6장 한계)
--   gap_analysis.scope_limited       : 추가 조사/원문 상한 도달 표시 (PRD 6장)
--   gap_result.change_detail         : 취소/완료 세부 상태 (설계서 4.4 검토사항)
--   gap_result.assessment_status     : RETRIEVAL_FAILED 추가 (PRD F5 조회 실패)
--   analysis_evidence.disclosed_at   : DATE (OpenDART rcept_dt 는 날짜 단위)
-- =========================================================

-- ---------------------------------------------------------
-- company : 기업 마스터
-- ---------------------------------------------------------
CREATE TABLE company (
    company_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corp_code         VARCHAR(8)   NOT NULL,
    corp_name         VARCHAR(200) NOT NULL,
    stock_code        VARCHAR(20),
    last_consulted_at TIMESTAMPTZ,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_company_corp_code UNIQUE (corp_code),
    CONSTRAINT ck_company_corp_code CHECK (corp_code ~ '^[0-9]{8}$')
);

COMMENT ON TABLE  company                   IS '기업 마스터';
COMMENT ON COLUMN company.corp_code         IS 'OpenDART 기업 고유번호 (8자리, 선행 0 보존)';
COMMENT ON COLUMN company.last_consulted_at IS '최근 상담일. 계획별 last_confirmed_at 이 없을 때 조회 시작 보조 기준';

-- ---------------------------------------------------------
-- rm_plan : 기업 x 분야 x 계획 단위 Mock CRM
-- ---------------------------------------------------------
CREATE TABLE rm_plan (
    plan_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         BIGINT        NOT NULL,
    domain             VARCHAR(30)   NOT NULL,
    scope              TEXT,
    knowledge_status   VARCHAR(30)   NOT NULL,
    plan_status        VARCHAR(30)   NOT NULL,
    last_confirmed_at  TIMESTAMPTZ,
    amount             NUMERIC(20,2),
    currency           VARCHAR(3),
    expected_at        DATE,
    expected_precision VARCHAR(20),
    source             TEXT,
    evidence_level     VARCHAR(30),
    valid_until        DATE,
    review_due_at      DATE,
    validity_status    VARCHAR(30),
    recorded_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    note               TEXT,

    CONSTRAINT fk_rm_plan_company FOREIGN KEY (company_id)
        REFERENCES company (company_id) ON DELETE RESTRICT,

    CONSTRAINT ck_rm_plan_domain CHECK (domain IN ('INVESTMENT', 'FUNDING', 'FX')),
    CONSTRAINT ck_rm_plan_knowledge_status CHECK (
        knowledge_status IN ('EXPLICIT_YES', 'EXPLICIT_NONE', 'UNCONFIRMED', 'UNRECORDED')),
    CONSTRAINT ck_rm_plan_plan_status CHECK (
        plan_status IN ('REVIEW', 'PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELED', 'NOT_APPLICABLE', 'UNKNOWN')),
    CONSTRAINT ck_rm_plan_expected_precision CHECK (
        expected_precision IN ('DAY', 'MONTH', 'QUARTER', 'HALF', 'YEAR')),
    CONSTRAINT ck_rm_plan_evidence_level CHECK (
        evidence_level IN ('DIRECT', 'DOCUMENT', 'INDIRECT', 'NONE')),
    CONSTRAINT ck_rm_plan_validity_status CHECK (
        validity_status IN ('UNVERIFIED', 'NO_CHANGE_EVIDENCE', 'RECHECK_NEEDED', 'PENDING')),
    CONSTRAINT ck_rm_plan_amount CHECK (amount >= 0),
    CONSTRAINT ck_rm_plan_currency CHECK (currency ~ '^[A-Z]{3}$'),

    -- PRD 3장: 명시적 없음 -> 해당 없음, 미확인/미기록 -> 알 수 없음
    CONSTRAINT ck_rm_plan_status_consistency CHECK (
           (knowledge_status = 'EXPLICIT_NONE' AND plan_status = 'NOT_APPLICABLE')
        OR (knowledge_status IN ('UNCONFIRMED', 'UNRECORDED') AND plan_status = 'UNKNOWN')
        OR (knowledge_status = 'EXPLICIT_YES' AND plan_status NOT IN ('NOT_APPLICABLE'))
    ),
    -- PRD 3장: 미기록 항목은 확인일이나 근거를 생성하지 않는다
    CONSTRAINT ck_rm_plan_unrecorded_empty CHECK (
        knowledge_status <> 'UNRECORDED'
        OR (last_confirmed_at IS NULL AND source IS NULL AND amount IS NULL)
    ),
    -- 금액은 통화와 함께, 예상 시기는 정밀도와 함께 저장
    CONSTRAINT ck_rm_plan_amount_currency CHECK (amount IS NULL OR currency IS NOT NULL),
    CONSTRAINT ck_rm_plan_expected_with_precision CHECK (
        (expected_at IS NULL) = (expected_precision IS NULL))
);

CREATE INDEX ix_rm_plan_company_domain ON rm_plan (company_id, domain);

COMMENT ON TABLE  rm_plan                    IS '기존 RM 계획 (Mock CRM). Agent 는 이 테이블을 자동 수정하지 않는다';
COMMENT ON COLUMN rm_plan.last_confirmed_at  IS '해당 항목을 실제 확인한 시점. recorded_at 으로 대체하지 않음';
COMMENT ON COLUMN rm_plan.amount             IS '미상은 NULL. 0 과 구분';
COMMENT ON COLUMN rm_plan.expected_at        IS '예상 시기의 대표 기준일. expected_precision 과 함께 해석';
COMMENT ON COLUMN rm_plan.valid_until        IS '고객이 명시한 유효기간. 없으면 NULL, 임의 생성 금지';

-- ---------------------------------------------------------
-- gap_analysis : 분석 실행 이력
-- ---------------------------------------------------------
CREATE TABLE gap_analysis (
    analysis_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id       BIGINT       NOT NULL,
    analysis_at      TIMESTAMPTZ  NOT NULL,
    query_start_at   TIMESTAMPTZ,
    query_end_at     TIMESTAMPTZ,
    query_ranges     JSONB,
    retrieval_status VARCHAR(30)  NOT NULL,
    crm_snapshot     JSONB        NOT NULL,
    rule_version     VARCHAR(30)  NOT NULL,
    model_version    VARCHAR(100),
    scope_limited    BOOLEAN      NOT NULL DEFAULT false,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_gap_analysis_company FOREIGN KEY (company_id)
        REFERENCES company (company_id) ON DELETE RESTRICT,

    CONSTRAINT ck_gap_analysis_retrieval_status CHECK (
        retrieval_status IN ('SUCCESS', 'PARTIAL_FAILURE', 'FAILURE')),
    CONSTRAINT ck_gap_analysis_query_range CHECK (
        query_start_at IS NULL OR query_end_at IS NULL OR query_start_at <= query_end_at),
    CONSTRAINT ck_gap_analysis_snapshot_object CHECK (jsonb_typeof(crm_snapshot) = 'object'),
    CONSTRAINT ck_gap_analysis_query_ranges_array CHECK (
        query_ranges IS NULL OR jsonb_typeof(query_ranges) = 'array')
);

CREATE INDEX ix_gap_analysis_company_at ON gap_analysis (company_id, analysis_at DESC);

COMMENT ON TABLE  gap_analysis               IS '분석 실행 단위';
COMMENT ON COLUMN gap_analysis.query_ranges  IS '계획별 실제 조회 범위 [{plan_id, domain, start_at, end_at, basis}]. basis: LAST_CONFIRMED / LAST_CONSULTED / DEFAULT_12M';
COMMENT ON COLUMN gap_analysis.crm_snapshot  IS '분석 당시 rm_plan 값의 불변 복사본. 수정하지 않는다';
COMMENT ON COLUMN gap_analysis.scope_limited IS '추가 조사 횟수 또는 원문 건수 상한 도달 여부';

-- ---------------------------------------------------------
-- gap_result : 계획/분야별 판정 결과
-- ---------------------------------------------------------
CREATE TABLE gap_result (
    result_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id         BIGINT       NOT NULL,
    plan_id             BIGINT,
    domain              VARCHAR(30)  NOT NULL,
    change_type         VARCHAR(30),
    change_detail       VARCHAR(30),
    assessment_status   VARCHAR(30)  NOT NULL,
    priority            SMALLINT,
    priority_reason     TEXT,
    changed_fields      JSONB,
    financial_signals   JSONB,
    questions           JSONB,
    environment_context JSONB,

    CONSTRAINT fk_gap_result_analysis FOREIGN KEY (analysis_id)
        REFERENCES gap_analysis (analysis_id) ON DELETE RESTRICT,
    CONSTRAINT fk_gap_result_plan FOREIGN KEY (plan_id)
        REFERENCES rm_plan (plan_id) ON DELETE RESTRICT,

    CONSTRAINT ck_gap_result_domain CHECK (domain IN ('INVESTMENT', 'FUNDING', 'FX')),
    CONSTRAINT ck_gap_result_change_type CHECK (
        change_type IN ('CONFLICT', 'NEW_INFO', 'SPECIFIED', 'CANCELED_OR_COMPLETED', 'NEEDS_CONFIRMATION')),
    CONSTRAINT ck_gap_result_change_detail CHECK (change_detail IN ('CANCELED', 'COMPLETED')),
    CONSTRAINT ck_gap_result_assessment_status CHECK (
        assessment_status IN ('CONFIRMED', 'PENDING', 'NO_CHANGE_EVIDENCE', 'RETRIEVAL_FAILED')),
    CONSTRAINT ck_gap_result_priority CHECK (priority BETWEEN 1 AND 3),

    -- PRD 5장: 확정 Gap / 추가 확인 필요 / 변경 근거 미발견 / 조회 실패 구분
    CONSTRAINT ck_gap_result_status_type CHECK (
           (assessment_status = 'CONFIRMED'
                AND COALESCE(change_type IN ('CONFLICT', 'NEW_INFO', 'SPECIFIED', 'CANCELED_OR_COMPLETED'), false))
        OR (assessment_status = 'PENDING'
                AND change_type IS NOT DISTINCT FROM 'NEEDS_CONFIRMATION')
        OR (assessment_status IN ('NO_CHANGE_EVIDENCE', 'RETRIEVAL_FAILED') AND change_type IS NULL)
    ),
    -- 취소/완료는 세부 상태 필수, 그 외에는 비움
    CONSTRAINT ck_gap_result_change_detail_usage CHECK (
        (change_type IS NOT DISTINCT FROM 'CANCELED_OR_COMPLETED') = (change_detail IS NOT NULL)
    ),
    -- 상충/구체화/취소·완료는 기존 계획이 있어야 성립. 신규 정보는 plan_id NULL 가능
    CONSTRAINT ck_gap_result_plan_required CHECK (
        change_type NOT IN ('CONFLICT', 'SPECIFIED', 'CANCELED_OR_COMPLETED') OR plan_id IS NOT NULL
    ),
    CONSTRAINT ck_gap_result_questions_array CHECK (
        questions IS NULL OR jsonb_typeof(questions) = 'array')
);

CREATE INDEX ix_gap_result_analysis ON gap_result (analysis_id);
CREATE INDEX ix_gap_result_plan     ON gap_result (plan_id);

COMMENT ON TABLE  gap_result                   IS '판정 결과. CRM 자동 수정 근거로 사용하지 않는다';
COMMENT ON COLUMN gap_result.priority          IS '상담 확인 순서 1=우선 확인, 2=다음 확인, 3=세부 갱신. 기업 위험등급 아님';
COMMENT ON COLUMN gap_result.changed_fields    IS '변경 필드 전후 값 [{field, before, after}]';
COMMENT ON COLUMN gap_result.financial_signals IS '직접 근거와 분리한 재무 신호';
COMMENT ON COLUMN gap_result.questions         IS '상담 질문 2~3개 (개수는 애플리케이션에서 검증)';

-- ---------------------------------------------------------
-- analysis_evidence : 판정 근거와 정정 연결
-- ---------------------------------------------------------
CREATE TABLE analysis_evidence (
    evidence_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    result_id          BIGINT       NOT NULL,
    rcept_no           VARCHAR(20)  NOT NULL,
    report_name        TEXT,
    disclosed_at       DATE,
    source_url         TEXT,
    evidence_text      TEXT,
    evidence_location  TEXT,
    original_rcept_no  VARCHAR(20),
    correction_details JSONB,
    retrieved_at       TIMESTAMPTZ  NOT NULL,

    CONSTRAINT fk_analysis_evidence_result FOREIGN KEY (result_id)
        REFERENCES gap_result (result_id) ON DELETE RESTRICT,

    CONSTRAINT ck_analysis_evidence_rcept_no CHECK (rcept_no ~ '^[0-9]{14}$'),
    CONSTRAINT ck_analysis_evidence_original_rcept_no CHECK (
        original_rcept_no IS NULL
        OR (original_rcept_no ~ '^[0-9]{14}$' AND original_rcept_no <> rcept_no))
);

CREATE INDEX ix_analysis_evidence_result   ON analysis_evidence (result_id);
CREATE INDEX ix_analysis_evidence_rcept_no ON analysis_evidence (rcept_no);

COMMENT ON TABLE  analysis_evidence                   IS '판정에 실제 사용한 공시 근거. 공시 원문 전체는 저장하지 않는다';
COMMENT ON COLUMN analysis_evidence.rcept_no          IS 'OpenDART 접수번호 (14자리)';
COMMENT ON COLUMN analysis_evidence.disclosed_at      IS '공시일. OpenDART rcept_dt 는 날짜 단위라 시각 선후를 단정하지 않는다';
COMMENT ON COLUMN analysis_evidence.original_rcept_no IS '정정 관계가 확인된 경우에만 원공시 접수번호';
